name: Create torrent
on:
  push:
    branches:
      - master

env:
  name_1: "batocera-odroidc2-30-20210302"
  comment_1: "By Genetik57 for batocera.org"
  url_1: "http://mirrors.o2switch.fr/batocera/odroidc2/stable/last/images/batocera-odroidc2-30-20210302.img.gz"
  file_name_1: "batocera-odroidc2-30-20210302.img.gz"
  piece_size_1: 19 # Check the README.md for recommended piece size

  name_2: "batocera-odroidn2-30-20210302"
  comment_2: "By Genetik57 for batocera.org"
  url_2: "http://mirrors.o2switch.fr/batocera/odroidn2/stable/last/images/batocera-odroidn2-30-20210302.img.gz"
  file_name_2: "batocera-odroidn2-30-20210302.img.gz"
  piece_size_2: 19 # Check the README.md for recommended piece size

  name_3: "batocera-odroidgoa-30-20210302"
  comment_3: "By Genetik57 for batocera.org"
  url_3: "http://mirrors.o2switch.fr/batocera/odroidgoa/stable/last/images/batocera-odroidgoa-30-20210302.img.gz"
  file_name_3: "batocera-odroidgoa-30-20210302.img.gz"
  piece_size_3: 19 # Check the README.md for recommended piece size

  name_4: "batocera-xu4-30-20210302"
  comment_4: "By Genetik57 for batocera.org"
  url_4: "http://mirrors.o2switch.fr/batocera/odroidxu4/stable/last/images/batocera-xu4-30-20210302.img.gz"
  file_name_4: "batocera-xu4-30-20210302.img.gz"
  piece_size_4: 19 # Check the README.md for recommended piece size

  name_5: "batocera-orangepi_pc-30-20210302"
  comment_5: "By Genetik57 for batocera.org"
  url_5: "http://mirrors.o2switch.fr/batocera/orangepi-pc/stable/last/images/batocera-orangepi_pc-30-20210302.img.gz"
  file_name_5: "batocera-orangepi_pc-30-20210302.img.gz"
  piece_size_5: 19 # Check the README.md for recommended piece size

  name_6: "batocera-rock960-30-20210305"
  comment_6: "By Genetik57 for batocera.org"
  url_6: "http://mirrors.o2switch.fr/batocera/rock960/stable/last/rc/images/batocera-rock960-30-20210305.img.gz"
  file_name_6: "batocera-rock960-30-20210305.img.gz"
  piece_size_6: 19 # Check the README.md for recommended piece size

  name_7: "batocera-rpi1-30-20210302"
  comment_7: "By Genetik57 for batocera.org"
  url_7: "http://mirrors.o2switch.fr/batocera/rpi1/stable/last/images/batocera-rpi1-30-20210302.img.gz"
  file_name_7: "batocera-rpi1-30-20210302.img.gz"
  piece_size_7: 19 # Check the README.md for recommended piece size

  name_8: "batocera-rpi2-30-20210302"
  comment_8: "By Genetik57 for batocera.org"
  url_8: "http://mirrors.o2switch.fr/batocera/rpi2/stable/last/images/batocera-rpi2-30-20210302.img.gz"
  file_name_8: "batocera-rpi2-30-20210302.img.gz"
  piece_size_8: 19 # Check the README.md for recommended piece size

  name_9: "batocera-rpi3-30-20210302"
  comment_9: "By Genetik57 for batocera.org"
  url_9: "http://mirrors.o2switch.fr/batocera/rpi3/stable/last/images/batocera-rpi3-30-20210302.img.gz"
  file_name_9: "batocera-rpi3-30-20210302.img.gz"
  piece_size_9: 19 # Check the README.md for recommended piece size

  name_10: "batocera-rpi4-30-20210302"
  comment_10: "By Genetik57 for batocera.org"
  url_10: "http://mirrors.o2switch.fr/batocera/rpi4/beta/last/images/batocera-rpi4-30-20210302.img.gz"
  file_name_10: "batocera-rpi4-30-20210302.img.gz"
  piece_size_10: 19 # Check the README.md for recommended piece size

  name_11: "batocera-s905-30-20210302"
  comment_11: "By Genetik57 for batocera.org"
  url_11: "http://mirrors.o2switch.fr/batocera/s905/stable/last/images/batocera-s905-30-20210302.img.gz"
  file_name_11: "batocera-s905-30-20210302.img.gz"
  piece_size_11: 19 # Check the README.md for recommended piece size

  name_12: "batocera-s912-30-20210302"
  comment_12: "By Genetik57 for batocera.org"
  url_12: "http://mirrors.o2switch.fr/batocera/s912/stable/last/images/batocera-s912-30-20210302.img.gz"
  file_name_12: "batocera-s912-30-20210302.img.gz"
  piece_size_12: 19 # Check the README.md for recommended piece size

  name_13: "batocera-x86-30-20210302"
  comment_13: "By Genetik57 for batocera.org"
  url_13: "http://mirrors.o2switch.fr/batocera/x86/stable/last/images/batocera-x86-30-20210302.img.gz"
  file_name_13: "batocera-x86-30-20210302.img.gz"
  piece_size_13: 20 # Check the README.md for recommended piece size

  name_14: "batocera-vim3-30-20210302"
  comment_14: "By Genetik57 for batocera.org"
  url_14: "http://mirrors.o2switch.fr/batocera/vim3/stable/last/images/batocera-vim3-30-20210302.img.gz"
  file_name_14: "batocera-vim3-30-20210302.img.gz"
  piece_size_14: 19 # Check the README.md for recommended piece size

  name_15: "batocera-x86_64-30-20210302"
  comment_15: "By Genetik57 for batocera.org"
  url_15: "http://mirrors.o2switch.fr/batocera/x86_64/stable/last/images/batocera-x86_64-30-20210302.img.gz"
  file_name_15: "batocera-x86_64-30-20210302.img.gz"
  piece_size_15: 20 # Check the README.md for recommended piece size

  name_16: "batocera-libretech_h5-30-20210302"
  comment_16: "By Genetik57 for batocera.org"
  url_16: "http://mirrors.o2switch.fr/batocera/libretech-h5/stable/last/images/batocera-libretech_h5-30-20210302.img.gz"
  file_name_16: "batocera-libretech_h5-30-20210302.img.gz"
  piece_size_16: 19 # Check the README.md for recommended piece size

  name_17: "batocera-miqi-30-20210302"
  comment_17: "By Genetik57 for batocera.org"
  url_17: "http://mirrors.o2switch.fr/batocera/miqi/stable/last/images/batocera-miqi-30-20210311.img.gz"
  file_name_17: "batocera-miqi-30-20210302.img.gz"
  piece_size_17: 19 # Check the README.md for recommended piece size

  name_18: "batocera-odroidc4-30-20210302"
  comment_18: "By Genetik57 for batocera.org"
  url_18: "http://mirrors.o2switch.fr/batocera/odroidc4/beta/last/images/batocera-odroidc4-30-20210302.img.gz"
  file_name_18: "batocera-odroidc4-30-20210302.img.gz"
  piece_size_18: 19 # Check the README.md for recommended piece size
  
  name_19: "batocera-tinkerboard-30-20210311"
  comment_19: "By Genetik57 for batocera.org"
  url_19: "http://mirrors.o2switch.fr/batocera/tinkerboard/beta/last/images/batocera-tinkerboard-30-20210311.img.gz"
  file_name_19: "batocera-tinkerboard-30-20210311.img.gz"
  piece_size_19: 19 # Check the README.md for recommended piece size

jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent

      - name: Download file 1
        run: wget -nv -O "$file_name_1" "$url_1"

      - name: Create torrent using mktorrent 1
        run: mktorrent -c "$comment_1" -l $piece_size_1 -o "${name_1}.torrent" -w "$url_1" "$file_name_1"

      - name: Delete file 1
        run: rm "$file_name_1"

      - name: Download file 2
        run: wget -nv -O "$file_name_2" "$url_2"

      - name: Create torrent using mktorrent 2
        run: mktorrent -c "$comment_2" -l $piece_size_2 -o "${name_2}.torrent" -w "$url_2" "$file_name_2"

      - name: Delete file 2
        run: rm "$file_name_2"

      - name: Download file 3
        run: wget -nv -O "$file_name_3" "$url_3"

      - name: Create torrent using mktorrent 3
        run: mktorrent -c "$comment_3" -l $piece_size_3 -o "${name_3}.torrent" -w "$url_3" "$file_name_3"

      - name: Delete file 3
        run: rm "$file_name_3"

      - name: Download file 4
        run: wget -nv -O "$file_name_4" "$url_4"

      - name: Create torrent using mktorrent 4
        run: mktorrent -c "$comment_4" -l $piece_size_4 -o "${name_4}.torrent" -w "$url_4" "$file_name_4"

      - name: Delete file 4
        run: rm "$file_name_4"

      - name: Download file 5
        run: wget -nv -O "$file_name_5" "$url_5"

      - name: Create torrent using mktorrent 5
        run: mktorrent -c "$comment_5" -l $piece_size_5 -o "${name_5}.torrent" -w "$url_5" "$file_name_5"

      - name: Delete file 5
        run: rm "$file_name_5"

      - name: Download file 6
        run: wget -nv -O "$file_name_6" "$url_6"

      - name: Create torrent using mktorrent 6
        run: mktorrent -c "$comment_6" -l $piece_size_6 -o "${name_6}.torrent" -w "$url_6" "$file_name_6"

      - name: Delete file 6
        run: rm "$file_name_6"

      - name: Download file 7
        run: wget -nv -O "$file_name_7" "$url_7"

      - name: Create torrent using mktorrent 7
        run: mktorrent -c "$comment_7" -l $piece_size_7 -o "${name_7}.torrent" -w "$url_7" "$file_name_7"

      - name: Delete file 7
        run: rm "$file_name_7"

      - name: Download file 8
        run: wget -nv -O "$file_name_8" "$url_8"

      - name: Create torrent using mktorrent 8
        run: mktorrent -c "$comment_8" -l $piece_size_8 -o "${name_8}.torrent" -w "$url_8" "$file_name_8"

      - name: Delete file 8
        run: rm "$file_name_8"

      - name: Download file 9
        run: wget -nv -O "$file_name_9" "$url_9"

      - name: Create torrent using mktorrent 9
        run: mktorrent -c "$comment_9" -l $piece_size_9 -o "${name_9}.torrent" -w "$url_9" "$file_name_9"

      - name: Delete file 9
        run: rm "$file_name_9"

      - name: Download file 10
        run: wget -nv -O "$file_name_10" "$url_10"

      - name: Create torrent using mktorrent 10
        run: mktorrent -c "$comment_10" -l $piece_size_10 -o "${name_10}.torrent" -w "$url_10" "$file_name_10"

      - name: Delete file 10
        run: rm "$file_name_10"

      - name: Download file 11
        run: wget -nv -O "$file_name_11" "$url_11"

      - name: Create torrent using mktorrent 11
        run: mktorrent -c "$comment_11" -l $piece_size_11 -o "${name_11}.torrent" -w "$url_11" "$file_name_11"

      - name: Delete file 11
        run: rm "$file_name_11"

      - name: Download file 12
        run: wget -nv -O "$file_name_12" "$url_12"

      - name: Create torrent using mktorrent 12
        run: mktorrent -c "$comment_12" -l $piece_size_12 -o "${name_12}.torrent" -w "$url_12" "$file_name_12"

      - name: Delete file 12
        run: rm "$file_name_12"

      - name: Download file 13
        run: wget -nv -O "$file_name_13" "$url_13"

      - name: Create torrent using mktorrent 13
        run: mktorrent -c "$comment_13" -l $piece_size_13 -o "${name_13}.torrent" -w "$url_13" "$file_name_13"

      - name: Delete file 13
        run: rm "$file_name_13"

      - name: Download file 14
        run: wget -nv -O "$file_name_14" "$url_14"

      - name: Create torrent using mktorrent 14
        run: mktorrent -c "$comment_14" -l $piece_size_14 -o "${name_14}.torrent" -w "$url_14" "$file_name_14"

      - name: Delete file 14
        run: rm "$file_name_14"

      - name: Download file 15
        run: wget -nv -O "$file_name_15" "$url_15"

      - name: Create torrent using mktorrent 15
        run: mktorrent -c "$comment_15" -l $piece_size_15 -o "${name_15}.torrent" -w "$url_15" "$file_name_15"

      - name: Delete file 15
        run: rm "$file_name_15"

      - name: Download file 16
        run: wget -nv -O "$file_name_16" "$url_16"

      - name: Create torrent using mktorrent 16
        run: mktorrent -c "$comment_16" -l $piece_size_16 -o "${name_16}.torrent" -w "$url_16" "$file_name_16"

      - name: Delete file 16
        run: rm "$file_name_16"

      - name: Download file 17
        run: wget -nv -O "$file_name_17" "$url_17"

      - name: Create torrent using mktorrent 17
        run: mktorrent -c "$comment_17" -l $piece_size_17 -o "${name_17}.torrent" -w "$url_17" "$file_name_17"

      - name: Delete file 17
        run: rm "$file_name_17"

      - name: Download file 18
        run: wget -nv -O "$file_name_18" "$url_18"

      - name: Create torrent using mktorrent 18
        run: mktorrent -c "$comment_18" -l $piece_size_18 -o "${name_18}.torrent" -w "$url_18" "$file_name_18"

      - name: Delete file 18
        run: rm "$file_name_18"

      - name: Download file 19
        run: wget -nv -O "$file_name_19" "$url_19"

      - name: Create torrent using mktorrent 19
        run: mktorrent -c "$comment_19" -l $piece_size_19 -o "${name_19}.torrent" -w "$url_19" "$file_name_19"

      - name: Delete file 19
        run: rm "$file_name_19"

      - name: Upload torrent file 1
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_1 }}
          path: ${{ env.name_1 }}.torrent

      - name: Upload torrent file 2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_2 }}
          path: ${{ env.name_2 }}.torrent

      - name: Upload torrent file 3
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_3 }}
          path: ${{ env.name_3 }}.torrent

      - name: Upload torrent file 4
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_4 }}
          path: ${{ env.name_4 }}.torrent

      - name: Upload torrent file 5
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_5 }}
          path: ${{ env.name_5 }}.torrent

      - name: Upload torrent file 6
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_6 }}
          path: ${{ env.name_6 }}.torrent

      - name: Upload torrent file 7
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_7 }}
          path: ${{ env.name_7 }}.torrent

      - name: Upload torrent file 8
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_8 }}
          path: ${{ env.name_8 }}.torrent

      - name: Upload torrent file 9
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_9 }}
          path: ${{ env.name_9 }}.torrent

      - name: Upload torrent file 10
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_10 }}
          path: ${{ env.name_10 }}.torrent

      - name: Upload torrent file 11
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_11 }}
          path: ${{ env.name_11 }}.torrent

      - name: Upload torrent file 12
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_12 }}
          path: ${{ env.name_12 }}.torrent

      - name: Upload torrent file 13
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_13 }}
          path: ${{ env.name_13 }}.torrent

      - name: Upload torrent file 14
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_14 }}
          path: ${{ env.name_14 }}.torrent

      - name: Upload torrent file 15
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_15 }}
          path: ${{ env.name_15 }}.torrent

      - name: Upload torrent file 16
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_16 }}
          path: ${{ env.name_16 }}.torrent

      - name: Upload torrent file 17
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_17 }}
          path: ${{ env.name_17 }}.torrent

      - name: Upload torrent file 18
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_18 }}
          path: ${{ env.name_18 }}.torrent

      - name: Upload torrent file 19
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_19 }}
          path: ${{ env.name_19 }}.torrent
